SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS EVENT_DATE,
	ORDERS.ORDER_MNEMONIC AS MED_PRODUCT,
	CV_ADMIN_ROUTE.DISPLAY AS ROUTE
FROM
	CE_MED_RESULT,
    CLINICAL_EVENT,
	CODE_VALUE CV_ADMIN_ROUTE,
	ENCNTR_ALIAS,
	ORDERS,
	PI_THERA_CLASS_VIEW
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
	AND (
	    ENCNTR_ALIAS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_CD NOT IN (37558239, 37556023)
	)
    AND (
        CLINICAL_EVENT.ORDER_ID = ORDERS.ORDER_ID
		AND ORDERS.ACTIVE_IND = 1
		AND ORDERS.CATALOG_TYPE_CD = 1363
    )
    AND (
        ORDERS.CATALOG_CD = PI_THERA_CLASS_VIEW.DRUG_CAT_CD
        AND PI_THERA_CLASS_VIEW.DRUG_CAT IN (
            'narcotic analgesic combinations', 
            'narcotic analgesics'
        )
    )
	AND (
		CLINICAL_EVENT.EVENT_ID = CE_MED_RESULT.EVENT_ID
		AND CE_MED_RESULT.ADMIN_ROUTE_CD = CV_ADMIN_ROUTE.CODE_VALUE
	)
	
UNION

SELECT DISTINCT
	ENCNTR_ALIAS.ALIAS AS FIN,
	TRUNC(pi_from_gmt(CLINICAL_EVENT.EVENT_END_DT_TM, (pi_time_zone(1, @Variable('BOUSER'))))) AS EVENT_DATE,
	CLINICAL_EVENT.RESULT_VAL AS MED_PRODUCT,
	CV_EVENT.DISPLAY AS ROUTE
FROM
    CLINICAL_EVENT,
    CODE_VALUE CV_EVENT,
	ENCNTR_ALIAS
WHERE
    ENCNTR_ALIAS.ALIAS IN @prompt('Enter value(s) for Alias','A',,Multi,Free,Persistent,,User:0)
	AND ENCNTR_ALIAS.ENCNTR_ALIAS_TYPE_CD = 619
	AND (
	    ENCNTR_ALIAS.ENCNTR_ID = CLINICAL_EVENT.ENCNTR_ID
		AND CLINICAL_EVENT.VALID_UNTIL_DT_TM > DATE '2099-12-31'
		AND CLINICAL_EVENT.EVENT_CD = 900876112
		AND CLINICAL_EVENT.EVENT_CD = CV_EVENT.CODE_VALUE
	)

