---
title: "ERAS Bariatric Surgery"
author: "Brian Gulbis"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")
```

```{r, message=FALSE}
library(tidyverse)
library(stringr)
library(lubridate)
library(DT)
# library(plotly)

dir_pre <- "../data/tidy/bari_2015"
dir_bsln <- "../data/tidy/bari_baseline"
dir_post <- "../data/tidy/bari_current"

data_patients <- read_rds(paste(dir_pre, "data_patients.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_patients.Rds", sep = "/")), 
              read_rds(paste(dir_post, "data_patients.Rds", sep = "/"))) %>%
    mutate(group = if_else(surgery_start >= mdy("7/1/2017", tz = "US/Central"), "recent", group))

data_demographics <- read_rds(paste(dir_pre, "data_demographics.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_demographics.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_demographics.Rds", sep = "/")))

data_opiods <- read_rds(paste(dir_pre, "data_opiods.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_opiods.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_opiods.Rds", sep = "/")))

data_nausea_meds <- read_rds(paste(dir_pre, "data_nv_meds.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_nv_meds.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_nv_meds.Rds", sep = "/")))

data_pain_meds <- read_rds(paste(dir_pre, "data_pain_meds.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_pain_meds.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_pain_meds.Rds", sep = "/")))

data_meds_cont <- read_rds(paste(dir_pre, "data_meds_cont.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_meds_cont.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_meds_cont.Rds", sep = "/"))) %>%
    filter(cum.dose > 0)

data_pain_scores_all <- read_rds(paste(dir_pre, "data_pain_scores_all.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_pain_scores_all.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_pain_scores_all.Rds", sep = "/")))

data_pain_scores_prior <- read_rds(paste(dir_pre, "data_pain_scores_prior.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_pain_scores_prior.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_pain_scores_prior.Rds", sep = "/")))

data_pca <- read_rds(paste(dir_bsln, "data_pca.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_post, "data_pca.Rds", sep = "/")))

data_revisit <- read_rds(paste(dir_pre, "data_revisit.Rds", sep = "/")) %>%
    bind_rows(read_rds(paste(dir_bsln, "data_revisit.Rds", sep = "/")),
              read_rds(paste(dir_post, "data_revisit.Rds", sep = "/")))

include <- select(data_patients, pie.id, group) 

pt_num <- include %>%
    ungroup() %>%
    count(group) %>%
    rename(pts = n)

pts_n <- spread(pt_num, group, pts)
```

```{r}
los_hdr <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Measure'),
            th(colspan = 2, paste0("2015 (N = ", pts_n$pre[1]), ")"),
            th(colspan = 2, paste0("2016 (N = ", pts_n$baseline[1]), ")"),
            th(colspan = 2, paste0("Jul-Sep 2017 (N = ", pts_n$recent[1]), ")")
        ),
        tr(
            lapply(rep(c('Mean', 'St Dev'), 3), th)
        )
    )
))

data_patients %>%
    select(pie.id, group, or.hours = or_hours, pacu.hours = pacu_hours, postop.los = postop_los) %>%
    mutate_at(c("or.hours", "pacu.hours", "postop.los"), as.numeric) %>%
    left_join(data_demographics[c("pie.id", "length.stay")], by = "pie.id") %>% 
    group_by(group) %>%
    summarize_at(c("or.hours", "pacu.hours", "postop.los", "length.stay"), funs(mean, sd), na.rm = TRUE) %>%
    gather(measure, value, -group) %>%
    separate(measure, c("measure", "test"), sep = "_") %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(measure, pre_mean, pre_sd, baseline_mean, baseline_sd, recent_mean, recent_sd) %>%
    mutate_at("measure", str_replace_all, pattern = c("length.stay" = "Length of Stay (days)",
                                                      "or.hours" = "OR Duration (hours)",
                                                      "pacu.hours" = "PACU Duration (hours)",
                                                      "postop.los" = "Post-Op LOS (days)")) %>%
    datatable(caption = "Durations",
              rownames = FALSE,
              # colnames = c("Measure", "Mean", "SD", "Mean", "SD"),
              container = los_hdr,
              options = list(dom = "t")) %>%
    formatRound(c("pre_mean", "pre_sd", "baseline_mean", "baseline_sd", "recent_mean", "recent_sd"), 1)
```

```{r}
data_patients %>%
    ungroup() %>%
    select(pie.id, group, dc_day) %>%
    filter(group != "current") %>%
    mutate_at("dc_day", as.numeric) %>%
    add_count(group) %>%
    group_by(group, n) %>%
    summarize_at("dc_day", funs(sum(. == 1, na.rm = TRUE))) %>%
    ungroup() %>%
    mutate(pct_pod = dc_day / n) %>%
    select(-n) %>%
    mutate_at("group", str_replace_all, pattern = c("baseline" = "2016", pre = "2015", recent = "Jul-Sep 2017")) %>%
    arrange(group) %>%
    datatable(caption = "Patients discharged on post-op day 1",
              rownames = FALSE,
              colnames = c("Group", "N", "%"),
              options = list(dom = "t")) %>%
    formatPercentage("pct_pod", 1)
```

```{r}
los_surg_hdr <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Surgeon'),
            th(colspan = 2, "2015"),
            th(colspan = 2, "2016"),
            th(colspan = 2, "Jul-Sep 2017")
        ),
        tr(
            lapply(rep(c('Mean', 'St Dev'), 3), th)
        )
    )
))

data_patients %>%
    select(pie.id, group, surgeon, or.hours = or_hours, pacu.hours = pacu_hours, postop.los = postop_los) %>%
    mutate_at(c("or.hours", "pacu.hours", "postop.los"), as.numeric) %>%
    left_join(data_demographics[c("pie.id", "length.stay")], by = "pie.id") %>% 
    filter(group != "current") %>%
    group_by(group, surgeon) %>%
    summarize_at(c("length.stay"), funs(mean, sd), na.rm = TRUE) %>%
    gather(measure, value, -group, -surgeon) %>%
    # separate(measure, c("measure", "test"), sep = "_") %>%
    unite(group_test, group, measure) %>%
    spread(group_test, value) %>%
    select(surgeon, pre_mean, pre_sd, baseline_mean, baseline_sd, recent_mean, recent_sd) %>%
    datatable(caption = "Length of Stay by Surgeon",
              rownames = FALSE,
              container = los_surg_hdr,
              options = list(dom = "t")) %>%
    formatRound(c("pre_mean", "pre_sd", "baseline_mean", "baseline_sd", "recent_mean", "recent_sd"), 1)
```

```{r}
los_surg_hdr <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Surgery'),
            th(colspan = 2, "2015"),
            th(colspan = 2, "2016"),
            th(colspan = 2, "Jul-Sep 2017")
        ),
        tr(
            lapply(rep(c('Mean', 'St Dev'), 3), th)
        )
    )
))

data_patients %>%
    select(pie.id, group, surgery, or.hours = or_hours, pacu.hours = pacu_hours, postop.los = postop_los) %>%
    mutate_at(c("or.hours", "pacu.hours", "postop.los"), as.numeric) %>%
    left_join(data_demographics[c("pie.id", "length.stay")], by = "pie.id") %>% 
    filter(group != "current") %>%
    group_by(group, surgery) %>%
    summarize_at(c("length.stay"), funs(mean, sd), na.rm = TRUE) %>%
    gather(measure, value, -group, -surgery) %>%
    # separate(measure, c("measure", "test"), sep = "_") %>%
    unite(group_test, group, measure) %>%
    spread(group_test, value) %>%
    select(surgery, pre_mean, pre_sd, baseline_mean, baseline_sd, recent_mean, recent_sd) %>%
    datatable(caption = "Length of Stay by Surgery",
              rownames = FALSE,
              container = los_surg_hdr,
              options = list(dom = "t")) %>%
    formatRound(c("pre_mean", "pre_sd", "baseline_mean", "baseline_sd", "recent_mean", "recent_sd"), 1)
```

```{r}
data_revisit %>%
    left_join(include, by = "pie.id") %>%
    filter(admit.type != "Preadmit Not OB") %>%
    count(group, visit.type) %>%
    left_join(pt_num, by = "group") %>%
    mutate(pct_pt = n / pts) %>%
    select(group, visit.type, pct_pt) %>%
    filter(group != "current") %>%
    spread(group, pct_pt) %>%
    select(visit.type, pre, baseline, recent) %>%
    datatable(caption = "Unplanned re-encounters at any MHHS facility within 30 days",
              rownames = FALSE,
              colnames = c("Visit Type", "2015", "2016", "Jul-Sep 2017"),
              options = list(dom = "t")) %>%
    formatPercentage(c("baseline", "pre", "recent"), 1)
```

```{r}
hdr <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Measure'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2016'),
            th(colspan = 2, 'Jul-Sep 2017')
        ),
        tr(
            lapply(rep(c('Median', 'IQR'), 3), th)
        )
    )
))

include %>%
    left_join(data_pain_scores_all[c("pie.id", "first.result", "last.result", "median.result", "max.result", "time.wt.avg")], by = "pie.id") %>%
    filter(group != "current") %>%
    group_by(group) %>%
    summarize_at(c("first.result", "last.result", "median.result", "max.result", "time.wt.avg"), funs(median, IQR), na.rm = TRUE) %>%
    gather(measure, value, -group) %>%
    separate(measure, c("measure", "test"), sep = "_") %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(measure, pre_median, pre_IQR, baseline_median, baseline_IQR, recent_median, recent_IQR) %>%
    mutate_at("measure", str_replace_all, pattern = c("first.result" = "First Pain Score",
                                                      "last.result" = "Last Pain Score",
                                                      "max.result" = "Highest Pain Score",
                                                      "median.result" = "Median Pain Score",
                                                      "time.wt.avg" = "Time-Weighted Avg Pain Score")) %>%
    datatable(caption = "Pain Scores",
              rownames = FALSE,
              # colnames = c("Measure", "Mean", "SD", "Mean", "SD"),
              container = hdr,
              options = list(dom = "t")) %>%
    formatRound(c("pre_median", "pre_IQR", "baseline_median", "baseline_IQR", "recent_median", "recent_IQR"), 1)
```

```{r}
include %>%
    left_join(data_pain_scores_prior[c("pie.id", "first.result", "last.result", "median.result", "max.result", "time.wt.avg")], by = "pie.id") %>%
    filter(group != "current") %>%
    group_by(group) %>%
    summarize_at(c("first.result", "last.result", "median.result", "max.result", "time.wt.avg"), funs(median, IQR), na.rm = TRUE) %>%
    gather(measure, value, -group) %>%
    separate(measure, c("measure", "test"), sep = "_") %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(measure, pre_median, pre_IQR, baseline_median, baseline_IQR, recent_median, recent_IQR) %>%
    mutate_at("measure", str_replace_all, pattern = c("first.result" = "First Pain Score",
                                                      "last.result" = "Last Pain Score",
                                                      "max.result" = "Highest Pain Score",
                                                      "median.result" = "Median Pain Score",
                                                      "time.wt.avg" = "Time-Weighted Avg Pain Score")) %>%
    datatable(caption = "Pre-Medication Pain Scores",
              rownames = FALSE,
              container = hdr,
              options = list(dom = "t")) %>%
    formatRound(c("pre_median", "pre_IQR", "baseline_median", "baseline_IQR", "recent_median", "recent_IQR"), 1)
```

```{r}
data_demographics %>%
    left_join(data_patients[c("pie.id", "group")], by = "pie.id") %>%
    group_by(group) %>%
    summarize_at("home_pain_med", sum, na.rm = TRUE) %>%
    left_join(pt_num, by = "group") %>%
    mutate(pct_pts = home_pain_med / pts) %>%
    select(-pts) %>%
    filter(group != "current") %>%
    mutate_at("group", str_replace_all, pattern = c("baseline" = "2016", pre = "2015", recent = "Jul-Sep 2017")) %>%
    arrange(group) %>%
    datatable(caption = "Patients on opiods prior to admission",
              rownames = FALSE,
              colnames = c("Group", "N", "%"),
              options = list(dom = "t")) %>%
    formatPercentage("pct_pts", 1)
```

```{r}
hdr_location <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Location'),
            th(rowspan = 2, valign="bottom", 'Route'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2016'),
            th(colspan = 2, 'Jul-Sep 2017')
        ),
        tr(
            lapply(rep(c('N', '%'), 3), th)
        )
    )
))

count_total_doses <- include %>%
    left_join(data_pain_meds, by = "pie.id") %>%
    filter(!is.na(timing)) %>%
    group_by(group) %>%
    summarize_at("num_doses", sum, na.rm = TRUE) %>%
    rename(total_doses = num_doses)

include %>%
    left_join(data_pain_meds, by = "pie.id") %>%
    filter(!is.na(timing)) %>%
    mutate_at("route", str_replace_all, pattern = c("IVPB" = "IV", "IVP" = "IV", "NG" = "PO")) %>%
    filter(group != "current") %>%
    group_by(group, timing, route) %>%
    summarize_at("num_doses", sum, na.rm = TRUE) %>%
    left_join(count_total_doses, by = "group") %>%
    mutate(pct_doses = num_doses / total_doses) %>%
    select(-total_doses) %>%
    gather(test, value, num_doses, pct_doses) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(timing, route, pre_num_doses, pre_pct_doses, everything()) %>%
    datatable(caption = "Location where pain medications are given",
              rownames = FALSE,
              container = hdr_location,
              options = list(dom = "t")) %>%
    formatPercentage(c("baseline_pct_doses", "pre_pct_doses", "recent_pct_doses"), 1)
```

* Medications given in the OR were not documented in the EMR in 2015 or 2016

```{r}
data_pca %>%
    left_join(include, by = "pie.id") %>%
    ungroup() %>%
    filter(group != "current") %>%
    count(group) %>%
    left_join(pt_num, by = "group") %>%
    mutate(num_pca = n / pts) %>%
    select(-pts) %>%
    mutate_at("group", str_to_title) %>%
    mutate_at("group", str_replace_all, pattern = c("Baseline" = "2016", "Recent" = "Jul-Sep 2017")) %>%
    datatable(caption = "PCA Use",
              rownames = FALSE,
              colnames = c("Group", "N", "%"),
              options = list(dom = "t")) %>%
    formatPercentage("num_pca", 1)
```

* PCA use was not documented in the EMR during 2015

```{r}
hdr_eq <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 2, valign="bottom", 'Measure'),
            th(rowspan = 2, valign="bottom", 'Location'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2016'),
            th(colspan = 2, 'Jul-Sep 2017')
        ),
        tr(
            lapply(rep(c('Median', 'IQR'), 3), th)
        )
    )
))

morph_eq <- data_opiods %>%
    mutate(morph_eq = case_when(med == "hydromorphone" & (route == "IV" | route == "IVP") ~ med.dose * 0.4,
                                med == "hydromorphone" & (route == "PO" | route == "NG") ~ med.dose / 0.8,
                                med == "fentanyl" & (route == "IV" | route == "IVP") ~ med.dose * 0.1,
                                med == "oxycodone" & (route == "PO" | route == "NG") ~ med.dose / 2.5,
                                med == "acetaminophen-hydrocodone" & med.dose.units == "mL" ~ med.dose * 10 / 15 / 2.5,
                                med == "acetaminophen-hydrocodone" & med.dose.units == "mg" ~ med.dose / 2.5,
                                med == "acetaminophen-codeine" & med.dose.units == "mL" ~ med.dose * 12 / 5 / 6,
                                med == "acetaminophen-codeine" & med.dose.units == "mg" ~ med.dose / 6,
                                med == "tramadol" & (route == "PO" | route == "NG") ~ med.dose / 25)) %>%
    group_by(pie.id, timing) %>%
    summarize_at("morph_eq", sum, na.rm = TRUE)

med_total_location <- include %>%
    left_join(morph_eq, by = "pie.id") %>%
    filter(!is.na(timing)) %>%
    group_by(group, timing) %>%
    summarize_at("morph_eq", funs(median, IQR), na.rm = TRUE) %>%
    mutate(measure = "Morphine Equivalents (Intermittent)") %>%
    gather(test, value, median, IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value)

med_total <- include %>%
    left_join(morph_eq, by = "pie.id") %>%
    group_by(group) %>%
    summarize_at("morph_eq", funs(median, IQR), na.rm = TRUE) %>%
    mutate(measure = "Morphine Equivalents (Intermittent)") %>%
    gather(test, value, median, IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    mutate(timing = "all")

pca_eq <- data_pca %>%
    filter(!is.na(pca_drug)) %>%
    mutate_at("pca_drug", str_to_lower) %>%
    mutate(drug = str_extract(pca_drug, "^[a-z]*"),
           morph_eq = case_when(drug == "hydromorphone" ~ total_dose * 0.4,
                                drug == "fentanyl" ~ total_dose * 0.1,
                                drug == "morphine" ~ total_dose)) %>%
    select(pie.id, morph_eq) %>%
    # bind_rows(morph_eq) %>%
    group_by(pie.id) %>%
    summarize_at("morph_eq", sum, na.rm = TRUE)

pca_total <- include %>%
    left_join(pca_eq, by = "pie.id") %>%
    group_by(group) %>%
    summarize_at("morph_eq", funs(median, IQR), na.rm = TRUE) %>%
    mutate(measure = "Morphine Equivalents (PCA)") %>%
    gather(test, value, median, IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    mutate(timing = "all")

pca_eq %>%
    bind_rows(morph_eq) %>%
    right_join(include, by = "pie.id") %>%
    filter(group != "current") %>%
    group_by(group) %>%
    summarize_at("morph_eq", funs(median, IQR), na.rm = TRUE) %>%
    mutate(measure = "Morphine Equivalents (All Sources)") %>%
    gather(test, value, median, IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    mutate(timing = "all") %>%
    bind_rows(med_total_location, med_total, pca_total) %>%
    select(measure, timing, pre_median, pre_IQR, baseline_median, baseline_IQR, recent_median, recent_IQR) %>%
    datatable(caption = "Opiod Total Dosage",
              rownames = FALSE,
              container = hdr_eq,
              options = list(dom = "t")) %>%
    formatRound(c("baseline_median", "baseline_IQR", "pre_median", "pre_IQR", "recent_median", "recent_IQR"), 1)

```

```{r}
hdr_meds <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 3, valign="bottom", 'Medication'),
            th(rowspan = 3, valign="bottom", 'Route'),
            th(colspan = 6, 'Number of Patients'),
            th(colspan = 6, 'Number of Doses'),
            th(colspan = 6, 'Median Total Dose')
        ),
        tr(
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017')
        ),
        tr(
            lapply(rep(c('N', '%'), 3), th),
            lapply(rep(c('Median', 'IQR'), 6), th)
        )
    )
))

meds_count <- include %>%
    left_join(data_pain_meds, by = "pie.id") %>%
    mutate_at("route", str_replace_all, pattern = c("IVPB" = "IV", "IVP" = "IV", "NG" = "PO")) %>%
    filter(!is.na(med), 
           timing == "floor") %>%
    ungroup() %>%
    distinct(pie.id, group, med, route) %>%
    count(group, med, route) %>%
    left_join(pt_num, by = "group") %>%
    mutate(med_pct = n / pts) %>%
    select(-pts)

include %>%
    left_join(data_pain_meds, by = "pie.id") %>%
    mutate_at("med.dose", funs(case_when(med == "acetaminophen-hydrocodone" & med.dose.units == "mL" ~ med.dose * 10 / 15,
                                         med == "acetaminophen-codeine" & med.dose.units == "mL" ~ med.dose * 12 / 5,
                                         TRUE ~ med.dose))) %>%
    mutate_at("route", str_replace_all, pattern = c("IVPB" = "IV", "IVP" = "IV", "NG" = "PO")) %>%
    filter(!is.na(med), 
           timing == "floor",
           group != "current") %>%
    group_by(group, med, route) %>%
    summarize_at(c("num_doses", "med.dose"), funs(median, IQR), na.rm = TRUE) %>%
    left_join(meds_count, by = c("group", "med", "route")) %>%
    gather(test, value, n, med_pct, num_doses_median, med.dose_median, num_doses_IQR, med.dose_IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(med, route, pre_n, pre_med_pct, baseline_n, baseline_med_pct, recent_n, recent_med_pct, pre_num_doses_median, pre_num_doses_IQR, baseline_num_doses_median, baseline_num_doses_IQR, recent_num_doses_median, recent_num_doses_IQR, pre_med.dose_median, pre_med.dose_IQR, baseline_med.dose_median, baseline_med.dose_IQR, recent_med.dose_median, recent_med.dose_IQR) %>%
    datatable(caption = "Pain Medications (Floor Only)",
              rownames = FALSE,
              container = hdr_meds,
              options = list(dom = "t")) %>%
    formatPercentage(c("baseline_med_pct", "pre_med_pct", "recent_med_pct"), 1)

```

```{r}
hdr_meds <- htmltools::withTags(table(
    class = 'display',
    thead(
        tr(
            th(rowspan = 3, valign="bottom", 'Medication'),
            th(rowspan = 3, valign="bottom", 'Route'),
            th(colspan = 6, 'Number of Patients'),
            th(colspan = 6, 'Number of Doses'),
            th(colspan = 6, 'Median Total Dose')
        ),
        tr(
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017'),
            th(colspan = 2, '2015'),
            th(colspan = 2, '2106'),
            th(colspan = 2, 'Jul-Sep 2017')
        ),
        tr(
            lapply(rep(c('N', '%'), 3), th),
            lapply(rep(c('Median', 'IQR'), 6), th)
        )
    )
))

meds_count <- include %>%
    left_join(data_nausea_meds, by = "pie.id") %>%
    mutate_at("route", str_replace_all, pattern = c("IVPB" = "IV", "IVP" = "IV", "NG" = "PO")) %>%
    filter(!is.na(med), 
           timing == "floor") %>%
    ungroup() %>%
    distinct(pie.id, group, med, route) %>%
    count(group, med, route) %>%
    left_join(pt_num, by = "group") %>%
    mutate(med_pct = n / pts) %>%
    select(-pts)

include %>%
    left_join(data_nausea_meds, by = "pie.id") %>%
    mutate_at("route", str_replace_all, pattern = c("IVPB" = "IV", "IVP" = "IV", "NG" = "PO")) %>%
    filter(!is.na(med), 
           timing == "floor",
           group != "current",
           route != "DIALYSIS") %>%
    group_by(group, med, route) %>%
    summarize_at(c("num_doses", "med.dose"), funs(median, IQR), na.rm = TRUE) %>%
    left_join(meds_count, by = c("group", "med", "route")) %>%
    gather(test, value, n, med_pct, num_doses_median, med.dose_median, num_doses_IQR, med.dose_IQR) %>%
    unite(group_test, group, test) %>%
    spread(group_test, value) %>%
    select(med, route, pre_n, pre_med_pct, baseline_n, baseline_med_pct, recent_n, recent_med_pct, pre_num_doses_median, pre_num_doses_IQR, baseline_num_doses_median, baseline_num_doses_IQR, recent_num_doses_median, recent_num_doses_IQR, pre_med.dose_median, pre_med.dose_IQR, baseline_med.dose_median, baseline_med.dose_IQR, recent_med.dose_median, recent_med.dose_IQR) %>%
    datatable(caption = "Nausea Medications (Floor Only)",
              rownames = FALSE,
              container = hdr_meds,
              options = list(dom = "t")) %>%
    formatPercentage(c("baseline_med_pct", "pre_med_pct", "recent_med_pct"), 1)

```
